# Generated by Django 3.0.4 on 2020-03-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blockchain',
            new_name='Chain',
        ),
    ]
